export const MENU_LIST_REQUEST = "MENU_LIST_REQUEST";
export const MENU_LIST_SUCCESS = "MENU_LIST_SUCCESS";
export const MENU_LIST_FAIL = "MENU_LIST_FAIL";

export const MENU_DETAILS_REQUEST = "MENU_DETAILS_REQUEST";
export const MENU_DETAILS_SUCCESS = "MENU_DETAILS_SUCCESS";
export const MENU_DETAILS_FAIL = "MENU_DETAILS_FAIL";

export const MENU_DELETE_REQUEST = "MENU_DELETE_REQUEST";
export const MENU_DELETE_SUCCESS = "MENU_DELETE_SUCCESS";
export const MENU_DELETE_FAIL = "MENU_DELETE_FAIL";

export const MENU_CREATE_REQUEST = "MENU_CREATE_REQUEST";
export const MENU_CREATE_SUCCESS = "MENU_CREATE_SUCCESS";
export const MENU_CREATE_FAIL = "MENU_CREATE_FAIL";
export const MENU_CREATE_RESET = "MENU_CREATE_RESET";

export const MENU_UPDATE_REQUEST = "MENU_UPDATE_REQUEST";
export const MENU_UPDATE_SUCCESS = "MENU_UPDATE_SUCCESS";
export const MENU_UPDATE_FAIL = "MENU_UPDATE_FAIL";
export const MENU_UPDATE_RESET = "MENU_UPDATE_RESET";

export const MENU_CREATE_REVIEW_REQUEST = "MENU_CREATE_REVIEW_REQUEST";
export const MENU_CREATE_REVIEW_SUCCESS = "MENU_CREATE_REVIEW_SUCCESS";
export const MENU_CREATE_REVIEW_FAIL = "MENU_CREATE_REVIEW_FAIL";
export const MENU_CREATE_REVIEW_RESET = "MENU_CREATE_REVIEW_RESET";

export const MENU_TYPE_LIST_REQUEST = "MENU_TYPE_LIST_REQUEST";
export const MENU_TYPE_LIST_SUCCESS = "MENU_TYPE_LIST_SUCCESS";
export const MENU_TYPE_LIST_FAIL = "MENU_TYPE_LIST_FAIL";

export const MENU_LIKE_REQUEST = "MENU_LIKE_REQUEST";
export const MENU_LIKE_SUCCESS = "MENU_LIKE_SUCCESS";
export const MENU_LIKE_FAIL = "MENU_LIKE_FAIL";
export const MENU_LIKE_RESET = "MENU_LIKE_RESET";
