export const TRAINING_LIST_REQUEST = "TRAINING_LIST_REQUEST";
export const TRAINING_LIST_SUCCESS = "TRAINING_LIST_SUCCESS";
export const TRAINING_LIST_FAIL = "TRAINING_LIST_FAIL";

export const TRAINING_DETAILS_REQUEST = "TRAINING_DETAILS_REQUEST";
export const TRAINING_DETAILS_SUCCESS = "TRAINING_DETAILS_SUCCESS";
export const TRAINING_DETAILS_FAIL = "TRAINING_DETAILS_FAIL";

export const TRAINING_DELETE_REQUEST = "TRAINING_DELETE_REQUEST";
export const TRAINING_DELETE_SUCCESS = "TRAINING_DELETE_SUCCESS";
export const TRAINING_DELETE_FAIL = "TRAINING_DELETE_FAIL";

export const TRAINING_CREATE_REQUEST = "TRAINING_CREATE_REQUEST";
export const TRAINING_CREATE_SUCCESS = "TRAINING_CREATE_SUCCESS";
export const TRAINING_CREATE_FAIL = "TRAINING_CREATE_FAIL";
export const TRAINING_CREATE_RESET = "TRAINING_CREATE_RESET";

export const TRAINING_UPDATE_REQUEST = "TRAINING_UPDATE_REQUEST";
export const TRAINING_UPDATE_SUCCESS = "TRAINING_UPDATE_SUCCESS";
export const TRAINING_UPDATE_FAIL = "TRAINING_UPDATE_FAIL";
export const TRAINING_UPDATE_RESET = "TRAINING_UPDATE_RESET";

export const TRAINING_CREATE_REVIEW_REQUEST = "TRAINING_CREATE_REVIEW_REQUEST";
export const TRAINING_CREATE_REVIEW_SUCCESS = "TRAINING_CREATE_REVIEW_SUCCESS";
export const TRAINING_CREATE_REVIEW_FAIL = "TRAINING_CREATE_REVIEW_FAIL";
export const TRAINING_CREATE_REVIEW_RESET = "TRAINING_CREATE_REVIEW_RESET";

export const TRAINING_TYPE_LIST_REQUEST = "TRAINING_TYPE_LIST_REQUEST";
export const TRAINING_TYPE_LIST_SUCCESS = "TRAINING_TYPE_LIST_SUCCESS";
export const TRAINING_TYPE_LIST_FAIL = "TRAINING_TYPE_LIST_FAIL";

export const TRAINING_LIKE_REQUEST = "TRAINING_LIKE_REQUEST";
export const TRAINING_LIKE_SUCCESS = "TRAINING_LIKE_SUCCESS";
export const TRAINING_LIKE_FAIL = "TRAINING_LIKE_FAIL";
export const TRAINING_LIKE_RESET = "TRAINING_LIKE_RESET";
